import os
import cv2
from datetime import datetime, timezone
from pathlib import Path
from flask import current_app
from app.extensions import db, socketio
from app.models.event import SecurityEvent
from app.models.alert import Alert
from app.services.alert_service import AlertService
from app.utils import setup_logger

logger = setup_logger('event_service')


class EventService:
    """
    Handles persistence of verified security events, automated snapshot writing,
    high-priority alert generation, and real-time Socket.IO incident broadcasting.
    """

    @staticmethod
    def record_security_event(event_dict, frame=None, app=None):
        """
        Records a candidate security event generated by the SecurityEngine.

        Args:
            event_dict (dict): Event parameters from SecurityEngine.
            frame (np.ndarray, optional): Annotated BGR frame to snapshot.
            app (Flask, optional): Flask application instance for background thread contexts.

        Returns:
            tuple: (SecurityEvent, Alert|None)
        """
        ctx_app = app or (current_app._get_current_object() if current_app else None)
        if ctx_app:
            with ctx_app.app_context():
                try:
                    return EventService._persist_event(event_dict, frame, ctx_app)
                finally:
                    db.session.close()
        else:
            try:
                return EventService._persist_event(event_dict, frame, None)
            finally:
                db.session.close()

    @staticmethod
    def _persist_event(event_dict, frame, app):
        camera_id = event_dict.get('camera_id')
        event_type = event_dict.get('event_type', 'security_event')
        risk_score = float(event_dict.get('risk_score', 50.0))
        risk_level = str(event_dict.get('risk_level', 'MEDIUM')).upper()
        confidence = float(event_dict.get('confidence', 0.85))
        description = event_dict.get('description', 'Detected security violation.')
        metadata = dict(event_dict.get('metadata', {}))
        now_dt = event_dict.get('timestamp') or datetime.now(timezone.utc)

        snapshot_rel_url = None

        # 1. Capture snapshot image if annotated frame is provided
        if frame is not None:
            try:
                snapshot_dir = app.config.get('SNAPSHOT_DIR') if app else 'data/snapshots'
                os.makedirs(snapshot_dir, exist_ok=True)

                ts_slug = datetime.now().strftime("%Y%m%d_%H%M%S_%f")[:19]
                track_id = metadata.get('track_id', '0')
                clean_type = event_type.replace('_', '-')
                filename = f"cam_{camera_id}_{clean_type}_{ts_slug}_trk{track_id}.jpg"

                full_path = Path(snapshot_dir) / filename
                cv2.imwrite(str(full_path), frame, [int(cv2.IMWRITE_JPEG_QUALITY), 80])

                snapshot_rel_url = f"/api/snapshots/{filename}"
                metadata['snapshot_filename'] = filename
                logger.debug(f"Saved security event snapshot to {full_path}")
            except Exception as e:
                logger.error(f"Failed to capture snapshot image for event: {e}")

        # 2. Persist SecurityEvent record
        try:
            event = SecurityEvent(
                camera_id=camera_id,
                event_type=event_type,
                timestamp=now_dt,
                confidence=confidence,
                risk_score=risk_score,
                risk_level=risk_level,
                description=description,
                snapshot_path=snapshot_rel_url,
                status='NEW',
                event_metadata=metadata
            )
            db.session.add(event)
            db.session.commit()
            logger.info(f"Recorded SecurityEvent #{event.id}: {event_type} [{risk_level} - Score: {risk_score}]")
        except Exception as e:
            logger.error(f"Database error persisting SecurityEvent: {e}")
            db.session.rollback()
            return None, None

        # 3. Create Alert for significant threats using AlertService (handles cooldowns & audit history)
        alert = None
        try:
            alert = AlertService.create_alert_from_event(event, event_dict=event_dict, app=app)
        except Exception as e:
            logger.error(f"Error during AlertService processing for Event #{event.id}: {e}")

        # 4. Broadcast Real-Time Socket.IO security_event notification
        try:
            event_payload = {
                'event_id': event.id,
                'camera_id': event.camera_id,
                'camera_name': event_dict.get('camera_name', f"Camera #{camera_id}"),
                'camera_location': event_dict.get('camera_location', 'Facility'),
                'event_type': event.event_type,
                'risk_score': event.risk_score,
                'risk_level': event.risk_level,
                'description': event.description,
                'timestamp': event.timestamp.isoformat() if hasattr(event.timestamp, 'isoformat') else str(event.timestamp),
                'snapshot_url': event.snapshot_path,
                'metadata': event.event_metadata or {}
            }
            socketio.emit('security_event', event_payload)
        except Exception as e:
            logger.debug(f"Socket.IO event broadcast skipped: {e}")

        return event, alert

